# 수학과 파이썬 복습
## 백터와 행렬

In [9]:
import numpy as np
x = np.array([1,2,3]) # 행 백터, 원소 3개 

print((x))
print(type(x))
y = np.array([[1], [2], [3]])
print(y)

[1 2 3]
<class 'numpy.ndarray'>
[[1]
 [2]
 [3]]


In [4]:
x.shape # x의 "형상" 원소가 3개, return type tuple, 

(3,)

In [5]:
x.ndim # 1차원이라 1로 리턴

1

In [8]:
W = np.array([[1,2,3], [4,5,6]]) # 2행 3열, tuple (2,3)
W.shape

(2, 3)

In [9]:
W.ndim #2-dimension "2" and "3" from W.shape

2

## 행렬의 원소별 연산

In [6]:
import numpy as np
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
W+X # 멤버별 합


array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [5]:
W*X # 멤버별 곱

array([[ 0,  2,  6],
       [12, 20, 30]])

## 브로드 캐스트

In [10]:
import numpy as np

In [13]:
A = np.array([[1,2], [3,4]]) #2차원
A* 10 # "10"은 0 차원 (scalar)이기 떄문에 에러를 내야하나 브로드캐스트 덕분에 scalar 곱셈으로 됨

array([[10, 20],
       [30, 40]])

In [15]:
A = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(A,b) # dot product "내적" 각각 원소별로 곱해서 합친다 1*4 + 2*5 + 3*6 = 4+10+18 = 32

32

In [17]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
np.dot(A,B) #행렬의 곱

array([[19, 22],
       [43, 50]])

In [18]:
A = np.array([[1,2], [3,4], [5,6]]) #(3,2)
B = np.array([[5,6], [7,8]]) # (2,2)
np.dot(A,B) #행렬의 곱 (3,2)

array([[19, 22],
       [43, 50],
       [67, 78]])