In [1]:
import numpy as np

A = np.array([[3,6],[2,3],[0,0],[0,0]]) # X = (4,2)
A

array([[3, 6],
       [2, 3],
       [0, 0],
       [0, 0]])

In [3]:
U = np.dot(A , A.T)  # (4, 2)(2, 4) => (4,4) A times A transpose
U

array([[45, 24,  0,  0],
       [24, 13,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [18]:
V = np.dot(A.T , A)  # (2, 4)(4, 2) => (2,2) A transpose times A
V

array([[13, 24],
       [24, 45]])

In [20]:
U_eigen ,U_vector= np.linalg.eig(U) # computes the eigenvalues and right eigenvectors of a square array
print(U_eigen)
U_vector

[57.8444102  0.1555898  0.         0.       ]


array([[ 0.8816746 , -0.47185793,  0.        ,  0.        ],
       [ 0.47185793,  0.8816746 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [21]:
V_eigen ,V_vector = np.linalg.eig(V.T)
print(V_eigen)
print(V_vector)

[ 0.1555898 57.8444102]
[[-0.8816746  -0.47185793]
 [ 0.47185793 -0.8816746 ]]


In [22]:
import numpy as np
from numpy.linalg import svd

A = np.array([[3, -1], 
              [1, 3], 
              [1, 1]])
U, S, VT = svd(A)

In [23]:
U

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -1.94289029e-16,  9.12870929e-01]])

In [24]:
S # 대각선 배열 S 자체는 (m,n) 사이즈이지만 대각산 배열이라 (m,m) 만 도출

array([3.46410162, 3.16227766])

In [25]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [26]:
np.diag(S, 1)[:, 1:] # 1차원으로 나온 S를 실제 대각선 배열로 만듦. 여기까지 특이값분해

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [4]:
U @ np.diag(S, 1)[:, 1:] @ VT # @ = matmul, 특이값분해된 U S VT 로 A 복원. 중요한 점은 U의 몇 개의 엘레멘트만 써도 X 근사치를 복원할 수 있다

NameError: name 'S' is not defined